In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(r"D:\Machine Learning projects\Stocks Predicter\US Stock Market Dataset.csv")

In [5]:
df.shape

(1013, 39)

In [6]:
df.head(10)

,Unnamed: 0,Date,Natural_Gas_Price,Natural_Gas_Vol.,Crude_oil_Price,Crude_oil_Vol.,Copper_Price,Copper_Vol.,Bitcoin_Price,Bitcoin_Vol.,...,Berkshire_Price,Berkshire_Vol.,Netflix_Price,Netflix_Vol.,Amazon_Price,Amazon_Vol.,Meta_Price,Meta_Vol.,Gold_Price,Gold_Vol.
0,0,2/2/2024,2.079,NaN,72.28,NaN,3.8215,NaN,"43,194.70",42650,...,"5,89,498",10580,564.64,4030000,171.81,117220000,474.99,84710000,"2,053.70",NaN
1,1,1/2/2024,2.050,161340.0,73.82,577940.0,3.8535,NaN,"43,081.40",47690,...,"5,81,600",9780,567.51,3150000,159.28,66360000,394.78,25140000,"2,071.10",260920.0
2,2,31-01-2024,2.100,142860.0,75.85,344490.0,3.9060,NaN,"42,580.50",56480,...,"5,78,020",9720,564.11,4830000,155.20,49690000,390.14,20010000,"2,067.40",238370.0
3,3,30-01-2024,2.077,139750.0,77.82,347240.0,3.9110,NaN,"42,946.20",55130,...,"5,84,680",9750,562.85,6120000,159.00,42290000,400.06,18610000,"2,050.90",214590.0
4,4,29-01-2024,2.490,3590.0,76.78,331930.0,3.8790,NaN,"43,299.80",45230,...,"5,78,800",13850,575.79,6880000,161.26,42840000,401.02,17790000,"2,034.90",1780.0
5,5,26-01-2024,2.712,73020.0,78.01,365460.0,3.8520,NaN,"41,811.30",69470,...,"5,82,300",10040,570.42,12770000,159.12,51050000,394.14,13160000,"2,026.60",410.0
6,6,25-01-2024,2.571,44980.0,77.36,320180.0,3.8690,NaN,"39,935.70",46300,...,"5,76,211",9350,562.00,9450000,157.75,43310000,393.18,15090000,"2,027.10",460.0
7,7,24-01-2024,2.641,65500.0,75.09,323730.0,3.8860,NaN,"40,086.00",58640,...,"5,70,977",9560,544.87,26350000,156.87,47640000,390.70,15700000,"2,025.40",800.0
8,8,23-01-2024,2.450,69160.0,74.37,306060.0,3.7935,NaN,"39,888.80",82670,...,"5,64,133",8640,492.19,14190000,156.02,34930000,385.20,15450000,"2,035.20",370.0
9,9,22-01-2024,2.419,121580.0,75.19,28910.0,3.7635,NaN,"39,556.40",85100,...,"5,58,316",11600,485.71,5210000,154.78,43690000,381.78,17490000,"2,031.50",330.0

In [7]:
df.isnull().sum()

Unnamed: 0             0
Date                   0
Natural_Gas_Price      0
Natural_Gas_Vol.       4
Crude_oil_Price        0
Crude_oil_Vol.        23
Copper_Price           0
Copper_Vol.           37
Bitcoin_Price          0
Bitcoin_Vol.           0
Platinum_Price         0
Platinum_Vol.        377
Ethereum_Price         0
Ethereum_Vol.          0
S&P_500_Price          0
Nasdaq_100_Price       0
Nasdaq_100_Vol.        1
Apple_Price            0
Apple_Vol.             0
Tesla_Price            0
Tesla_Vol.             0
Microsoft_Price        0
Microsoft_Vol.         0
Silver_Price           0
Silver_Vol.           46
Google_Price           0
Google_Vol.            0
Nvidia_Price           0
Nvidia_Vol.            0
Berkshire_Price        0
Berkshire_Vol.         0
Netflix_Price          0
Netflix_Vol.           0
Amazon_Price           0
Amazon_Vol.            0
Meta_Price             0
Meta_Vol.              0
Gold_Price             0
Gold_Vol.              2
dtype: int64

In [8]:
df.dropna(inplace=True)

In [9]:
df.isnull().sum()

Unnamed: 0           0
Date                 0
Natural_Gas_Price    0
Natural_Gas_Vol.     0
Crude_oil_Price      0
Crude_oil_Vol.       0
Copper_Price         0
Copper_Vol.          0
Bitcoin_Price        0
Bitcoin_Vol.         0
Platinum_Price       0
Platinum_Vol.        0
Ethereum_Price       0
Ethereum_Vol.        0
S&P_500_Price        0
Nasdaq_100_Price     0
Nasdaq_100_Vol.      0
Apple_Price          0
Apple_Vol.           0
Tesla_Price          0
Tesla_Vol.           0
Microsoft_Price      0
Microsoft_Vol.       0
Silver_Price         0
Silver_Vol.          0
Google_Price         0
Google_Vol.          0
Nvidia_Price         0
Nvidia_Vol.          0
Berkshire_Price      0
Berkshire_Vol.       0
Netflix_Price        0
Netflix_Vol.         0
Amazon_Price         0
Amazon_Vol.          0
Meta_Price           0
Meta_Vol.            0
Gold_Price           0
Gold_Vol.            0
dtype: int64

In [10]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [78]:
object_cols = df.select_dtypes(include=['object']).columns
print(object_cols)

Index([], dtype='object')

In [64]:
df['Bitcoin_Price'] = df['Bitcoin_Price'].str.replace(',', '').astype(float)

In [65]:
df['Platinum_Price'] = df['Platinum_Price'].str.replace(',', '').astype(float)

In [66]:
df['Ethereum_Price'] = df['Ethereum_Price'].str.replace(',', '').astype(float)

In [69]:
df['Nasdaq_100_Price'] = df['Nasdaq_100_Price'].str.replace(',', '').astype(float)

In [70]:
df['Gold_Price'] = df['Gold_Price'].str.replace(',', '').astype(float)

In [77]:
df['Berkshire_Price'] = df['Berkshire_Price'].str.replace(',', '').astype(float)

In [79]:
df

,Natural_Gas_Price,Natural_Gas_Vol.,Crude_oil_Price,Crude_oil_Vol.,Copper_Price,Copper_Vol.,Bitcoin_Price,Bitcoin_Vol.,Platinum_Price,Platinum_Vol.,...,Berkshire_Price,Berkshire_Vol.,Netflix_Price,Netflix_Vol.,Amazon_Price,Amazon_Vol.,Meta_Price,Meta_Vol.,Gold_Price,Gold_Vol.
28,2.572,84550.0,73.89,251980.0,3.9175,70080.0,43865.9,48960,970.3,26550.0,...,541000.0,7700,491.61,2750000,153.84,35950000,354.09,15220000,2041.8,540.0
29,2.447,125260.0,74.22,273360.0,3.9060,66320.0,43662.8,70190,974.0,30010.0,...,543740.0,8150,489.27,4520000,152.12,50000000,349.28,15990000,2038.1,260.0
30,2.492,170440.0,73.44,25690.0,3.8980,84950.0,42259.3,55290,965.8,25860.0,...,554650.0,7500,495.02,3840000,153.79,42890000,350.36,17660000,2042.6,470.0
31,2.503,154300.0,72.47,73940.0,3.8520,54990.0,42659.7,61580,954.3,26230.0,...,551182.0,10460,486.12,6410000,154.07,62510000,344.62,18360000,2030.9,250.0
32,2.491,189240.0,71.43,95510.0,3.8905,73670.0,41929.0,45280,952.6,38070.0,...,544478.0,8430,472.06,7840000,149.97,110090000,334.92,31780000,2026.0,630.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,2.238,206250.0,41.22,399000.0,2.8020,310.0,11592.0,517000,977.4,340.0,...,314334.0,440,494.73,5910000,158.37,78720000,268.44,72770000,2028.0,398130.0
864,2.165,161990.0,41.95,359610.0,2.9190,290.0,11757.1,554850,1020.8,820.0,...,307455.0,440,509.08,3730000,161.25,78810000,265.28,45240000,2069.4,312760.0
865,2.191,182430.0,42.19,491270.0,2.9250,30.0,11735.1,570830,994.9,260.0,...,305200.0,560,502.11,4310000,160.25,78600000,249.12,13090000,2049.3,366380.0
866,2.193,230890.0,41.70,451580.0,2.9030,50.0,11184.7,485790,961.0,200.0,...,300330.0,270,509.64,5610000,156.94,93890000,249.83,17180000,2021.0,274420.0
867,2.101,381970.0,41.01,338330.0,2.9205,40.0,11224.4,470240,938.0,90.0,...,298800.0,470,498.62,5880000,155.59,101490000,251.96,23130000,1986.3,178750.0

In [80]:
df.drop("Date",axis=1,inplace=True)

KeyError: "['Date'] not found in axis"

In [81]:
df

,Natural_Gas_Price,Natural_Gas_Vol.,Crude_oil_Price,Crude_oil_Vol.,Copper_Price,Copper_Vol.,Bitcoin_Price,Bitcoin_Vol.,Platinum_Price,Platinum_Vol.,...,Berkshire_Price,Berkshire_Vol.,Netflix_Price,Netflix_Vol.,Amazon_Price,Amazon_Vol.,Meta_Price,Meta_Vol.,Gold_Price,Gold_Vol.
28,2.572,84550.0,73.89,251980.0,3.9175,70080.0,43865.9,48960,970.3,26550.0,...,541000.0,7700,491.61,2750000,153.84,35950000,354.09,15220000,2041.8,540.0
29,2.447,125260.0,74.22,273360.0,3.9060,66320.0,43662.8,70190,974.0,30010.0,...,543740.0,8150,489.27,4520000,152.12,50000000,349.28,15990000,2038.1,260.0
30,2.492,170440.0,73.44,25690.0,3.8980,84950.0,42259.3,55290,965.8,25860.0,...,554650.0,7500,495.02,3840000,153.79,42890000,350.36,17660000,2042.6,470.0
31,2.503,154300.0,72.47,73940.0,3.8520,54990.0,42659.7,61580,954.3,26230.0,...,551182.0,10460,486.12,6410000,154.07,62510000,344.62,18360000,2030.9,250.0
32,2.491,189240.0,71.43,95510.0,3.8905,73670.0,41929.0,45280,952.6,38070.0,...,544478.0,8430,472.06,7840000,149.97,110090000,334.92,31780000,2026.0,630.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,2.238,206250.0,41.22,399000.0,2.8020,310.0,11592.0,517000,977.4,340.0,...,314334.0,440,494.73,5910000,158.37,78720000,268.44,72770000,2028.0,398130.0
864,2.165,161990.0,41.95,359610.0,2.9190,290.0,11757.1,554850,1020.8,820.0,...,307455.0,440,509.08,3730000,161.25,78810000,265.28,45240000,2069.4,312760.0
865,2.191,182430.0,42.19,491270.0,2.9250,30.0,11735.1,570830,994.9,260.0,...,305200.0,560,502.11,4310000,160.25,78600000,249.12,13090000,2049.3,366380.0
866,2.193,230890.0,41.70,451580.0,2.9030,50.0,11184.7,485790,961.0,200.0,...,300330.0,270,509.64,5610000,156.94,93890000,249.83,17180000,2021.0,274420.0
867,2.101,381970.0,41.01,338330.0,2.9205,40.0,11224.4,470240,938.0,90.0,...,298800.0,470,498.62,5880000,155.59,101490000,251.96,23130000,1986.3,178750.0

In [40]:
df.drop(["S&P_500_Price"],axis=1,inplace=True)

In [82]:
df.shape

(609, 36)

In [102]:
y = df.drop(["Natural_Gas_Vol.","Crude_oil_Vol.","Copper_Vol.","Bitcoin_Vol.","Platinum_Vol.","Ethereum_Vol.","Nasdaq_100_Vol.","Apple_Vol.","Tesla_Vol.","Microsoft_Vol.","Silver_Vol.","Google_Vol.","Nvidia_Vol.","Berkshire_Vol.","Netflix_Vol.","Amazon_Vol.","Meta_Vol.","Gold_Vol."],axis=1)
X = df.drop(y,axis=1)

In [103]:
X = X.reset_index(drop=True)

In [104]:
y

,Natural_Gas_Price,Crude_oil_Price,Copper_Price,Bitcoin_Price,Platinum_Price,Ethereum_Price,Nasdaq_100_Price,Apple_Price,Tesla_Price,Microsoft_Price,Silver_Price,Google_Price,Nvidia_Price,Berkshire_Price,Netflix_Price,Amazon_Price,Meta_Price,Gold_Price
28,2.572,73.89,3.9175,43865.9,970.3,2239.62,16757.41,194.68,254.50,373.54,24.585,140.42,489.90,541000.0,491.61,153.84,354.09,2041.8
29,2.447,74.22,3.9060,43662.8,974.0,2202.19,16554.16,194.83,247.14,370.62,24.631,138.34,481.11,543740.0,489.27,152.12,349.28,2038.1
30,2.492,73.44,3.8980,42259.3,965.8,2177.44,16811.86,196.94,257.22,373.26,24.321,136.65,496.04,554650.0,495.02,153.79,350.36,2042.6
31,2.503,72.47,3.8520,42659.7,954.3,2218.80,16729.80,195.89,252.08,372.65,24.107,135.80,500.77,551182.0,486.12,154.07,344.62,2030.9
32,2.491,71.43,3.8905,41929.0,952.6,2220.41,16623.45,197.57,253.50,370.73,24.154,132.60,488.90,544478.0,472.06,149.97,334.92,2026.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,2.238,41.22,2.8020,11592.0,977.4,379.57,11139.39,111.11,96.85,212.48,27.540,74.92,112.00,314334.0,494.73,158.37,268.44,2028.0
864,2.165,41.95,2.9190,11757.1,1020.8,394.83,11267.08,113.90,99.31,216.35,28.400,75.25,113.36,307455.0,509.08,161.25,265.28,2069.4
865,2.191,42.19,2.9250,11735.1,994.9,400.79,11125.44,110.06,99.00,212.94,26.890,73.95,112.87,305200.0,502.11,160.25,249.12,2049.3
866,2.193,41.70,2.9030,11184.7,961.0,389.62,11096.54,109.67,99.13,213.29,26.028,73.67,112.28,300330.0,509.64,156.94,249.83,2021.0
867,2.101,41.01,2.9205,11224.4,938.0,385.80,11055.08,108.94,99.00,216.54,24.417,74.14,110.10,298800.0,498.62,155.59,251.96,1986.3

In [105]:
from sklearn.model_selection import train_test_split

In [106]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [107]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScaler object
scaler = StandardScaler()

# Fit the scaler to the data
scaler.fit(X_train)

# Transform the data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [108]:
X_train

,Natural_Gas_Vol.,Crude_oil_Vol.,Copper_Vol.,Bitcoin_Vol.,Platinum_Vol.,Ethereum_Vol.,Nasdaq_100_Vol.,Apple_Vol.,Tesla_Vol.,Microsoft_Vol.,Silver_Vol.,Google_Vol.,Nvidia_Vol.,Berkshire_Vol.,Netflix_Vol.,Amazon_Vol.,Meta_Vol.,Gold_Vol.
155,106970.0,305340.0,1940.0,150180,23960.0,1890000,223730000.0,71050000,74460000,22840000,75670.0,35480000,57760000,1720,5200000,73020000,31420000,249490.0
247,192860.0,497750.0,320.0,76600,1750.0,568420,203270000.0,77250000,60990000,28530000,58940.0,54970000,37690000,1960,8230000,102620000,88610000,139810.0
543,186660.0,411030.0,130.0,186130,180.0,6530000,177200000.0,114460000,65120000,25230000,114860.0,28620000,38330000,220,4240000,92950000,13890000,246780.0
577,146580.0,73760.0,160.0,63480,2260.0,8950000,537370000.0,287100000,259220000,55230000,53090.0,63060000,69850000,750,6720000,177850000,28130000,176070.0
153,127670.0,379860.0,2670.0,115810,15780.0,1180000,224250000.0,66250000,81930000,20860000,42480.0,40940000,49290000,1960,6330000,57870000,23890000,151260.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,189060.0,259520.0,87260.0,51290,10770.0,420800,229510000.0,45390000,123860000,29770000,49820.0,48710000,39770000,5100,4660000,43810000,26100000,490.0
106,87550.0,59630.0,5870.0,423430,4260.0,1110000,231530000.0,81470000,60230000,26830000,44270.0,23040000,56970000,3150,17910000,47280000,22170000,141170.0
270,99070.0,317630.0,38420.0,41060,18490.0,338510,199760000.0,104700000,104690000,28920000,46320.0,28680000,39240000,2740,3070000,63870000,14560000,168310.0
435,41280.0,361540.0,1780.0,84080,12520.0,1450000,168170000.0,66020000,88310000,31010000,65270.0,44390000,16460000,1540,3760000,76540000,15310000,147950.0
102,123600.0,334270.0,11230.0,431150,14280.0,1160000,275270000.0,96030000,63750000,34180000,82520.0,31630000,66330000,3090,11210000,65130000,31710000,243050.0

In [109]:
y_train

,Natural_Gas_Price,Crude_oil_Price,Copper_Price,Bitcoin_Price,Platinum_Price,Ethereum_Price,Nasdaq_100_Price,Apple_Price,Tesla_Price,Microsoft_Price,Silver_Price,Google_Price,Nvidia_Price,Berkshire_Price,Netflix_Price,Amazon_Price,Meta_Price,Gold_Price
397,5.730,108.43,3.6200,19262.9,871.3,1058.94,11585.68,138.93,227.26,259.58,19.667,108.74,145.23,415850.0,179.95,109.56,160.03,1801.5
494,4.232,91.32,4.4675,43833.9,1020.7,3140.18,14571.25,171.66,302.45,300.95,23.076,139.20,247.28,474900.0,402.10,157.94,224.91,1821.8
800,2.888,37.14,3.1570,15577.9,902.8,455.72,12091.35,118.69,143.32,223.72,25.662,87.99,145.62,313885.0,514.73,165.57,293.41,1951.7
835,2.048,41.11,3.1140,10933.0,946.1,384.20,10936.98,106.84,147.38,200.39,27.129,72.55,121.89,327601.0,469.96,147.75,252.53,1962.1
395,6.297,102.73,3.5770,21637.8,865.8,1238.15,12109.05,146.35,244.54,268.40,19.188,118.78,158.58,419200.0,189.27,116.33,172.19,1739.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,2.011,80.70,4.0155,28036.7,1016.8,1872.35,13062.60,164.66,185.06,291.60,25.093,108.42,270.37,478005.0,339.33,102.06,216.10,2011.9
345,7.752,85.73,3.5045,19538.9,912.6,1376.00,11953.27,154.48,309.07,244.52,19.358,103.07,133.82,421339.0,243.63,124.66,148.02,1678.2
517,3.815,76.08,4.4215,46430.2,954.0,3764.24,16501.77,182.01,399.93,334.75,22.810,144.99,301.21,454300.0,597.37,170.40,338.54,1800.1
687,2.873,62.94,4.4870,55036.5,1249.5,2665.24,13960.28,134.39,234.91,261.97,26.410,114.55,153.82,411400.0,505.55,170.87,303.57,1778.8
341,6.992,78.74,3.3370,19293.5,856.5,1327.96,11311.24,150.43,275.33,237.92,18.910,98.74,125.16,404485.0,226.41,113.78,140.41,1655.6

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 609 entries, 28 to 867
Data columns (total 36 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Natural_Gas_Price  609 non-null    float64
 1   Natural_Gas_Vol.   609 non-null    float64
 2   Crude_oil_Price    609 non-null    float64
 3   Crude_oil_Vol.     609 non-null    float64
 4   Copper_Price       609 non-null    float64
 5   Copper_Vol.        609 non-null    float64
 6   Bitcoin_Price      609 non-null    float64
 7   Bitcoin_Vol.       609 non-null    int64
 8   Platinum_Price     609 non-null    float64
 9   Platinum_Vol.      609 non-null    float64
 10  Ethereum_Price     609 non-null    float64
 11  Ethereum_Vol.      609 non-null    int64
 12  Nasdaq_100_Price   609 non-null    float64
 13  Nasdaq_100_Vol.    609 non-null    float64
 14  Apple_Price        609 non-null    float64
 15  Apple_Vol.         609 non-null    int64
 16  Tesla_Price        609 non-null    float64
 17  Tesla_Vol.         609 non-null    int64
 18  Microsoft_Price    609 non-null    float64
 19  Microsoft_Vol.     609 non-null    int64
 20  Silver_Price       609 non-null    float64
 21  Silver_Vol.        609 non-null    float64
 22  Google_Price       609 non-null    float64
 23  Google_Vol.        609 non-null    int64
 24  Nvidia_Price       609 non-null    float64
 25  Nvidia_Vol.        609 non-null    int64
 26  Berkshire_Price    609 non-null    float64
 27  Berkshire_Vol.     609 non-null    int64
 28  Netflix_Price      609 non-null    float64
 29  Netflix_Vol.       609 non-null    int64
 30  Amazon_Price       609 non-null    float64
 31  Amazon_Vol.        609 non-null    int64
 32  Meta_Price         609 non-null    float64
 33  Meta_Vol.          609 non-null    int64
 34  Gold_Price         609 non-null    float64
 35  Gold_Vol.          609 non-null    float64
dtypes: float64(25), int64(11)
memory usage: 176.0 KB

In [118]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor()
rf.fit(X_train,y_train)

RandomForestRegressor()

In [129]:
X_train

,Natural_Gas_Vol.,Crude_oil_Vol.,Copper_Vol.,Bitcoin_Vol.,Platinum_Vol.,Ethereum_Vol.,Nasdaq_100_Vol.,Apple_Vol.,Tesla_Vol.,Microsoft_Vol.,Silver_Vol.,Google_Vol.,Nvidia_Vol.,Berkshire_Vol.,Netflix_Vol.,Amazon_Vol.,Meta_Vol.,Gold_Vol.
155,106970.0,305340.0,1940.0,150180,23960.0,1890000,223730000.0,71050000,74460000,22840000,75670.0,35480000,57760000,1720,5200000,73020000,31420000,249490.0
247,192860.0,497750.0,320.0,76600,1750.0,568420,203270000.0,77250000,60990000,28530000,58940.0,54970000,37690000,1960,8230000,102620000,88610000,139810.0
543,186660.0,411030.0,130.0,186130,180.0,6530000,177200000.0,114460000,65120000,25230000,114860.0,28620000,38330000,220,4240000,92950000,13890000,246780.0
577,146580.0,73760.0,160.0,63480,2260.0,8950000,537370000.0,287100000,259220000,55230000,53090.0,63060000,69850000,750,6720000,177850000,28130000,176070.0
153,127670.0,379860.0,2670.0,115810,15780.0,1180000,224250000.0,66250000,81930000,20860000,42480.0,40940000,49290000,1960,6330000,57870000,23890000,151260.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,189060.0,259520.0,87260.0,51290,10770.0,420800,229510000.0,45390000,123860000,29770000,49820.0,48710000,39770000,5100,4660000,43810000,26100000,490.0
106,87550.0,59630.0,5870.0,423430,4260.0,1110000,231530000.0,81470000,60230000,26830000,44270.0,23040000,56970000,3150,17910000,47280000,22170000,141170.0
270,99070.0,317630.0,38420.0,41060,18490.0,338510,199760000.0,104700000,104690000,28920000,46320.0,28680000,39240000,2740,3070000,63870000,14560000,168310.0
435,41280.0,361540.0,1780.0,84080,12520.0,1450000,168170000.0,66020000,88310000,31010000,65270.0,44390000,16460000,1540,3760000,76540000,15310000,147950.0
102,123600.0,334270.0,11230.0,431150,14280.0,1160000,275270000.0,96030000,63750000,34180000,82520.0,31630000,66330000,3090,11210000,65130000,31710000,243050.0

In [143]:
from sklearn.metrics import r2_score

y_pred = rf.predict(X_test)

r2_score(y_test,y_pred)

0.8342509797460786

In [137]:
from sklearn.metrics import r2_score

y_pred = rf.predict([[106970.0, 305340.0, 1940.0, 150180, 23960.0, 1890000, 223730000.0, 
                        71050000, 74460000, 22840000, 75670.0, 35480000, 57760000, 1720, 
                        5200000, 73020000, 31420000, 249490.0]])


np.set_printoptions(precision=2, suppress=True)

print(y_pred)

[[     5.82    103.2       3.67  21853.12    893.38   1224.3   11893.12
     140.09    231.06    260.09     20.21    110.76    151.92 415609.81
     214.65    115.75    176.52   1788.38]]

c:\Users\Dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [132]:
y_train

,Natural_Gas_Price,Crude_oil_Price,Copper_Price,Bitcoin_Price,Platinum_Price,Ethereum_Price,Nasdaq_100_Price,Apple_Price,Tesla_Price,Microsoft_Price,Silver_Price,Google_Price,Nvidia_Price,Berkshire_Price,Netflix_Price,Amazon_Price,Meta_Price,Gold_Price
397,5.730,108.43,3.6200,19262.9,871.3,1058.94,11585.68,138.93,227.26,259.58,19.667,108.74,145.23,415850.0,179.95,109.56,160.03,1801.5
494,4.232,91.32,4.4675,43833.9,1020.7,3140.18,14571.25,171.66,302.45,300.95,23.076,139.20,247.28,474900.0,402.10,157.94,224.91,1821.8
800,2.888,37.14,3.1570,15577.9,902.8,455.72,12091.35,118.69,143.32,223.72,25.662,87.99,145.62,313885.0,514.73,165.57,293.41,1951.7
835,2.048,41.11,3.1140,10933.0,946.1,384.20,10936.98,106.84,147.38,200.39,27.129,72.55,121.89,327601.0,469.96,147.75,252.53,1962.1
395,6.297,102.73,3.5770,21637.8,865.8,1238.15,12109.05,146.35,244.54,268.40,19.188,118.78,158.58,419200.0,189.27,116.33,172.19,1739.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,2.011,80.70,4.0155,28036.7,1016.8,1872.35,13062.60,164.66,185.06,291.60,25.093,108.42,270.37,478005.0,339.33,102.06,216.10,2011.9
345,7.752,85.73,3.5045,19538.9,912.6,1376.00,11953.27,154.48,309.07,244.52,19.358,103.07,133.82,421339.0,243.63,124.66,148.02,1678.2
517,3.815,76.08,4.4215,46430.2,954.0,3764.24,16501.77,182.01,399.93,334.75,22.810,144.99,301.21,454300.0,597.37,170.40,338.54,1800.1
687,2.873,62.94,4.4870,55036.5,1249.5,2665.24,13960.28,134.39,234.91,261.97,26.410,114.55,153.82,411400.0,505.55,170.87,303.57,1778.8
341,6.992,78.74,3.3370,19293.5,856.5,1327.96,11311.24,150.43,275.33,237.92,18.910,98.74,125.16,404485.0,226.41,113.78,140.41,1655.6

In [145]:
import pickle 

pickle.dump(rf,open('model.pkl','wb'))